### ISSUE TITLE
Bug: Meta description is set to slider css style when using "Syna" theme

### ISSUE THREAD

**Issue by schoettl** [tbiering/hugo-slider-shortcode#18]
Hi, any idea why hugo with Syna theme generates the following meta tag, only on the homepage `/index.html` (where the slider is used)?

```html
  <meta name="description" content="#slide-window { position: relative; width: 500px; height: 300px; overflow: hidden; top: 0px; left: 0px; } #slides-list { width: ... ">
```
Same for the `twitter:description` meta tag.

It's exactly the CSS from the `<style>` element in gallery-slider.html in my layouts/shortcodes/ folder.

The other meta tags (e.g. `og:description`) are generated correctly.

**Comment by schoettl** [comment]
It seems that Syna just uses the first element's content as meta description. If that happens to be a `<style>` tag, the description will be CSS... :/

**Comment by tbiering** [comment]
Thanks for following up on your findings. As this is a bug from the theme itself, there is not much we can do.
